language: rust

install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install v11.10
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

script:
  - npm install
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist
  on:
    branch: master
